const Data={
    models:{
        options:{
            option1:'/assets/House.glb',
            option2:'/assets/model.glb',
            nodes:[
                ['main_Facia001',
                'main_Glass',
                'main_Ceiling002',
                'main_Door__Panel',
                'main_Plaster_Int002',
                'main_Roofing__Sheets001',
                'main_Plaster_1002',
                'main_Tiles_terrazzo',
                'main_Plaster_2002',
                'main_Frame',
                'main_Railing'],
                ['main_Facia001',
                'main_Glass',
                'main_Ceiling002',
                'main_Plaster_Int002',
                'main_Door__Panel',
                'main_Roofing__Sheets001',
                'main_Plaster_1002',
                'main_Tiles_terrazzo',
                'main_Plaster_2002',
                'main_Frame',
                'main_Railing']
            ]
        }
    },
    map360:[
            '/textures/360_01.jpg',
            '/textures/360_02.jpg'
        ],
    renderImgs:[
            '/imgs/0001.jpg',
            '/imgs/0002.jpg',
            '/imgs/0003.jpg',
            '/imgs/0004.jpg',
            '/imgs/0005.jpg',
            '/imgs/0006.jpg',
            '/imgs/0007.jpg',
            '/imgs/0008.jpg',
            '/imgs/0009.jpg',
            '/imgs/0010.jpg',
            '/imgs/0011.jpg',
        ],
    ui:{
        menuColor:'#0000007d',
        popupColor:'#00000099',
        icons:{
            icons360:'/ui/icons/360s.png',
            back:'/ui/icons/back.png',
            balcony:'/ui/icons/balcony.png',
            bathrm:'/ui/icons/bathrm.png',
            bedrm:'/ui/icons/bedrm.png',
            close:'/ui/icons/close.png',
            dinning:'/ui/icons/dinning.png',
            driveway:'/ui/icons/driveway.png',
            foyer:'/ui/icons/foyer.png',
            gym:'/ui/icons/gym.png',
            home:'/ui/icons/home.png',
            kitchen:'/ui/icons/kitchen.png',
            levels:'/ui/icons/levels.png',
            lounge:'/ui/icons/lounge.png',
            next:'/ui/icons/next.png',
            pool:'/ui/icons/pool.png',
            render:'/ui/icons/renders.png',
            scullery:'/ui/icons/scullery.png',
            study:'/ui/icons/study.png',
            toilet:'/ui/icons/toilet.png',
            walkin_closet:'/ui/icons/walkin_closet.png',
        },
        top:{
            
        },
        right:{
            
        },
        bottom:{
            
        }
    }
}

export default Data